### ISSUE TITLE
Allow custom events to be passed to Notify()

### ISSUE THREAD

**Issue by StoneVT** [SvenSommer/LegoSorter.HardwareController#2]
I'm posting this to keep a list of some ideas for Sunday:

- [ ]  Rename ``EventHandler::Notify()`` -> ``EventHandler->TriggerEvent(Event* e)``
   - This allows any ``Event``-derived object to be passed on to the ``HandleEvent(Event* e)`` method of the registered handlers.

**Comment by SvenSommer** [comment]
Hey,
I did a first implementation here:
https://github.com/SvenSommer/LegoSorter.HardwareController/pull/4
